flower_api_public_sales_payment_methods_findall:
    path:     /paymentmethods
    defaults: { _controller: FlowerSalesBundle:Api\PaymentMethod:getAll }
    methods: [GET]

flower_api_public_sales_sale_items_findall:
    path:     /saleitems
    defaults: { _controller: FlowerSalesBundle:Api\SaleItems:getAll }
    methods: [GET]
