flower_api_sales_payment_method_show:
    path:     /paymentmethod/{id}
    defaults: { _controller: FlowerSalesBundle:Api\PaymentMethod:getById }
    methods: [GET]

flower_api_sales_payment_method_findall:
    path:     /paymentmethod
    defaults: { _controller: FlowerSalesBundle:Api\PaymentMethod:getAll }
    methods: [GET]

flower_api_sales_status_findall:
    path:     /salestatus
    defaults: { _controller: FlowerSalesBundle:Api\SaleStatus:getAll }
    methods: [GET]

flower_api_sales_sale_item_show:
    path:     /saleitem/{id}
    defaults: { _controller: FlowerSalesBundle:Api\SaleItem:getById }
    methods: [GET]
flower_api_sales_sale_show:
    path:     /sale/{id}
    defaults: { _controller: FlowerSalesBundle:Api\Sale:get }
    methods: [GET]

flower_api_sales_sale_item_findall:
    path:     /saleitem
    defaults: { _controller: FlowerSalesBundle:Api\SaleItem:getAll }
    methods: [GET]

flower_api_sales_sale_item_new:
    path:     /create
    defaults: { _controller: FlowerSalesBundle:Api\Sale:create }
    methods: [POST]

flower_api_sales_sale_item_edit:
    path:     /edit/{sale}
    defaults: { _controller: FlowerSalesBundle:Api\Sale:update }
    methods: [PUT]
