services:
#    flower_core.example:
#        class: Flower\CoreBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    form.api.sale:
        class: Flower\SalesBundle\Form\Type\Api\SaleType
        arguments: ["@security.context"]
        tags:
            - { name: form.type, alias: contact_type }

    sales.service.sale:
        class: Flower\SalesBundle\Service\SaleService
        arguments: ['@service_container']
    sales.service.excelexport:
        class: Flower\SalesBundle\Service\ExcelExportService
        arguments: ['@service_container']