<?php

namespace Flower\ModelBundle\Entity\Sales;

use Doctrine\ORM\EntityRepository;

/**
 * PaymentMethodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentMethodRepository extends EntityRepository
{
}
