<?php

namespace Flower\SalesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SaleCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaleCategoryRepository extends EntityRepository
{
}
