<?php

namespace Flower\SalesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SaleStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaleStatusRepository extends EntityRepository
{
}
